[project]
name = "webreaderz"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "lxml>=5.3.2",
    "pytest>=8.3.5",
]
